### ISSUE TITLE
[xenial] No option to display single picture or to leave in album view

### ISSUE THREAD

**Issue by ennedin** [ubports/gallery-app#60]
After creating a new album and opening it the only way back to the main view is closing and re-opening the app. Also there is no reaction (e.g. a detail view of the picture) when tapping one single picture in the album.
Issue on hammerhead with xenial (16.04).

**Comment by StefWe** [comment]
@Flohack74 can you pin the lable "bug" to this report?

**Comment by Flohack74** [comment]
Yes and do we know if this is a regression from 15.04?

**Comment by StefWe** [comment]
@Flohack74 i don't understand what you mean with regression.
I use arale with 15.04 and don't have problems with the album view.

**Comment by Flohack74** [comment]
So this is a regression since it worked in 15.04 but doesnt in 16.04 :)

**Comment by StefWe** [comment]
Right. I can not test it by myself, i don't have a xenial device.
But if someone else is testing the album view please report your experience.

**Comment by StefWe** [comment]
I can confirm this issue on hammerhead with xenial build r369

**Comment by StefWe** [comment]
hopefully we made some progress here as soon as #63 is fixed

**Comment by StefWe** [comment]
My logfile from the gallery-app 16.04 version: https://paste.ubuntu.com/p/5TCfRKDNM2/
My logfile from the gallery-app 15.04 version: https://paste.ubuntu.com/p/3td4ZDy6jb/

Here they have the same issue: https://github.com/timsueberkrueb/ubuntu-hangups/issues/70#issuecomment-392269297
But they write this don't effect the function of the app.

**Comment by cibersheep** [comment]
Is missing the PageHeader :)
On Vivid
![imatge](https://user-images.githubusercontent.com/6640041/47756085-05cd8300-dca1-11e8-91b2-5d476ab000b5.png)

On Xenial
![imatge](https://user-images.githubusercontent.com/6640041/47756098-141b9f00-dca1-11e8-955a-7e4275b914b9.png)

**Comment by JassMan23** [comment]
ennedin also complained about not being able to view a single picture from within the album. I also find this frustrating since it insists on making 2 (almost square) cropped pics per page and over half of them have heads cropped at nose level with no way to see a full face. This occurs in hammerhead xenial OTA5(20181012) and dev builds up to 705. I don't know if this is a regression since I have only used albums since my phone upgraded itself from Vivid - with frustration because of the 2 bugs listed (this second one may be a feature request).

If ennedin's request/bug is a new feature can I suggest that you need the a choice to view 1 or 2 pics per page (on a page by page basis) and choose the orientation and cropping for each picture. Once you have set up your album you also need to be able to open a picture for zoom/pan.

**Comment by TronFortyTwo** [comment]
fixed with #96
